import type { Metadata } from 'next';
import './globals.css';
import { inter, outfit } from './fonts';
import Providers from '@/lib/themeProvider';
import Header from '@/components/header/Header';
import Footer from '@/components/footer/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <Providers>
          <main className="bg-background">
            <div className="parent-container">
              <Header />
              <div className="">{children}</div>
              <Footer />
            </div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
